---
title: C28105 | Dokumentacja firmy Microsoft
ms.custom: ''
ms.date: 2018-06-30
ms.prod: visual-studio-dev14
ms.reviewer: ''
ms.suite: ''
ms.technology:
- vs-devops-test
ms.tgt_pltfrm: ''
ms.topic: article
f1_keywords:
- C28105
helpviewer_keywords:
- C28105
ms.assetid: 5afdec78-30eb-470c-980f-93d0cb3e74cc
caps.latest.revision: 5
author: corob-msft
ms.author: gewarren
manager: ghogen
ms.openlocfilehash: 836a1571190a79579c47774e4dfd9c0aa0b508c7
ms.sourcegitcommit: 55f7ce2d5d2e458e35c45787f1935b237ee5c9f8
ms.translationtype: MT
ms.contentlocale: pl-PL
ms.lasthandoff: 08/22/2018
ms.locfileid: "42678551"
---
# <a name="c28105"></a>C28105
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

Najnowszą wersję tego tematu znajduje się w temacie [C28105](https://docs.microsoft.com/visualstudio/code-quality/c28105).  
  
Ostrzeżenie C28105: Wyciek zasobów z powodu wyjątku  
  
 Podany zasób nie jest zwalniana, gdy wyjątek jest zgłaszany. Instrukcja określona przez ścieżkę może zgłosić wyjątek. To ostrzeżenie jest podobny do ostrzeżenie [C28103](../code-quality/c28103.md), z tą różnicą, że w tym przypadku chodzi o wyjątku.  
  
## <a name="example"></a>Przykład  
 Poniższy kod generuje to ostrzeżenie:  
  
```  
res = KeSaveFloatingPointState(buffer);  
  
res = AllocateResource(Resource);  
char *p2 = new char[10]; // could throw  
  
delete[] p2;  
FreeResource(Resource)  
```  
  
 Poniższy kod pozwala uniknąć tego ostrzeżenia:  
  
```  
res = AllocateResource(Resource);  
char *p2;  
  
try {  
    p2 = new char[10];  
} catch (std::bad_alloc *e) {  
    // just handle the throw  
    ;  
}  
FreeResource(Resource)  
```



